#!/usr/bin/env python3
"""Stronger PathBudget feasibility test against locality-aware baselines.

This follow-up checks whether PathBudget is more than "keep TP local".

ASTRA usage:
  * This script reuses the ASTRA logical-topology calibration generated by
    tools/pathbudget_feasibility.py when available.

External model:
  * Depth reach, per-circuit bandwidth, latency, loss, port/radix cost, and
    circuit/wavelength budget.
  * Total optical resource budget is fixed. Each policy gets the same 12 circuit
    units and can only decide how to split them among TP/PP/DP.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from statistics import mean
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
AXES = ("TP", "PP", "DP")
TOTAL_RESOURCE_UNITS = 12
INJECTION_CAP_GBPS = 2400.0


@dataclass(frozen=True)
class WorkloadSpec:
    name: str
    params_b: float
    layers: int
    hidden: int
    seq_len: int
    tp: int
    pp: int
    dp: int
    microbatches: int
    microbatch_size: int
    critical_tp: float
    critical_pp: float
    critical_dp: float


@dataclass(frozen=True)
class AxisSignature:
    axis: str
    payload_gb: float
    events: int
    group_size: int
    min_depth: int
    critical_weight: float
    frequency: str


@dataclass(frozen=True)
class DepthSpec:
    depth: int
    reach: int
    bandwidth_per_unit_gbps: float
    latency_us: float
    port_cost_per_unit: float
    loss_db: float
    reconfig_us: float


@dataclass(frozen=True)
class Regime:
    name: str
    description: str
    depths: dict[int, DepthSpec]


@dataclass(frozen=True)
class Budget:
    loss_name: str
    loss_db: float
    port_name: str
    port_units: float


@dataclass(frozen=True)
class Policy:
    name: str
    depths: dict[str, int]
    units: dict[str, int]


@dataclass
class EvalResult:
    workload: str
    regime: str
    loss_budget: str
    port_budget: str
    policy: str
    depth_budget: str
    time_s: float | None
    port_usage: float
    max_loss_db: float
    feasible: bool
    failure_reason: str


@dataclass
class ComparisonRow:
    workload: str
    regime: str
    loss_budget: str
    port_budget: str
    baseline: str
    baseline_depth_budget: str
    pathbudget_depth_budget: str
    baseline_time_s: float | None
    pathbudget_time_s: float | None
    oracle_time_s: float | None
    speedup: float | None
    oracle_gap_pct: float | None
    verdict: str


def workload_specs() -> list[WorkloadSpec]:
    return [
        WorkloadSpec(
            name="LLaMA-13B-like_DP-heavy_TP8_PP2_DP64",
            params_b=13.0,
            layers=40,
            hidden=5120,
            seq_len=4096,
            tp=8,
            pp=2,
            dp=64,
            microbatches=32,
            microbatch_size=1,
            critical_tp=0.55,
            critical_pp=0.35,
            critical_dp=0.75,
        ),
        WorkloadSpec(
            name="GPT-3-175B-like_mixed_TP8_PP8_DP16",
            params_b=175.0,
            layers=96,
            hidden=12288,
            seq_len=2048,
            tp=8,
            pp=8,
            dp=16,
            microbatches=32,
            microbatch_size=1,
            critical_tp=0.75,
            critical_pp=0.65,
            critical_dp=0.55,
        ),
        WorkloadSpec(
            name="Megatron-310B-like_PP-heavy_TP8_PP16_DP8",
            params_b=310.0,
            layers=96,
            hidden=16384,
            seq_len=2048,
            tp=8,
            pp=16,
            dp=8,
            microbatches=32,
            microbatch_size=1,
            critical_tp=0.70,
            critical_pp=0.90,
            critical_dp=0.45,
        ),
        WorkloadSpec(
            name="Megatron-530B-like_large_PP-heavy_TP8_PP16_DP8",
            params_b=530.0,
            layers=105,
            hidden=20480,
            seq_len=2048,
            tp=8,
            pp=16,
            dp=8,
            microbatches=32,
            microbatch_size=1,
            critical_tp=0.70,
            critical_pp=0.95,
            critical_dp=0.45,
        ),
    ]


def min_depth_for_reach(group_size: int) -> int:
    if group_size <= 16:
        return 1
    if group_size <= 64:
        return 2
    return 3


def signatures(workload: WorkloadSpec) -> dict[str, AxisSignature]:
    bytes_per_elem = 2
    activation_bytes = (
        workload.microbatch_size
        * workload.seq_len
        * workload.hidden
        * bytes_per_elem
        / workload.tp
    )
    tp_factor = 2.0 * (workload.tp - 1) / workload.tp
    dp_factor = 2.0 * (workload.dp - 1) / workload.dp
    tp_payload = workload.layers * workload.microbatches * 4 * activation_bytes * tp_factor
    pp_payload = max(1, workload.pp - 1) * workload.microbatches * 2 * activation_bytes
    dp_payload = workload.params_b * 1e9 * bytes_per_elem / (workload.tp * workload.pp) * dp_factor
    pp_span = workload.tp * workload.pp
    return {
        "TP": AxisSignature(
            "TP",
            tp_payload / 1e9,
            workload.layers * workload.microbatches * 4,
            workload.tp,
            min_depth_for_reach(workload.tp),
            workload.critical_tp,
            "layer/microbatch frequent",
        ),
        "PP": AxisSignature(
            "PP",
            pp_payload / 1e9,
            max(1, workload.pp - 1) * workload.microbatches * 2,
            pp_span,
            min_depth_for_reach(pp_span),
            workload.critical_pp,
            "microbatch pipeline boundary",
        ),
        "DP": AxisSignature(
            "DP",
            dp_payload / 1e9,
            max(1, math.ceil(workload.layers / 4)),
            workload.dp,
            3,
            workload.critical_dp,
            "bucketed global gradient sync",
        ),
    }


def regimes() -> list[Regime]:
    return [
        Regime(
            "reach_only_depth_is_costly",
            "deeper depth gives reach but not extra bandwidth per circuit",
            {
                1: DepthSpec(1, 16, 200, 0.45, 0.25, 2.5, 0),
                2: DepthSpec(2, 64, 175, 1.50, 0.50, 6.0, 1),
                3: DepthSpec(3, 1024, 150, 5.00, 1.00, 10.0, 10),
            },
        ),
        Regime(
            "extra_parallelism_bandwidth_steering",
            "deeper tiers can get more bandwidth per circuit but consume more port budget",
            {
                1: DepthSpec(1, 16, 150, 0.45, 0.25, 2.5, 0),
                2: DepthSpec(2, 64, 225, 1.50, 0.75, 6.5, 1),
                3: DepthSpec(3, 1024, 300, 5.00, 1.50, 10.5, 10),
            },
        ),
        Regime(
            "deep_oversubscribed_global_bottleneck",
            "global depth has reach but lower per-circuit bandwidth due to shared OCS contention",
            {
                1: DepthSpec(1, 16, 200, 0.45, 0.25, 2.5, 0),
                2: DepthSpec(2, 64, 150, 1.80, 0.60, 6.5, 1),
                3: DepthSpec(3, 1024, 75, 6.50, 1.25, 11.0, 10),
            },
        ),
    ]


def budgets() -> list[Budget]:
    return [
        Budget(loss_name, loss, port_name, port)
        for loss_name, loss in {"strict": 10.0, "medium": 14.0, "relaxed": 20.0}.items()
        for port_name, port in {"low": 7.0, "medium": 10.0, "high": 16.0}.items()
    ]


def resource_allocations(total_units: int = TOTAL_RESOURCE_UNITS) -> Iterable[dict[str, int]]:
    for tp in range(1, total_units - 1):
        for pp in range(1, total_units - tp):
            dp = total_units - tp - pp
            if dp >= 1:
                yield {"TP": tp, "PP": pp, "DP": dp}


def depth_assignments() -> Iterable[dict[str, int]]:
    for tp in (1, 2, 3):
        for pp in (1, 2, 3):
            for dp in (1, 2, 3):
                yield {"TP": tp, "PP": pp, "DP": dp}


def shortest_feasible_depths(sigs: dict[str, AxisSignature]) -> dict[str, int]:
    return {axis: sig.min_depth for axis, sig in sigs.items()}


def equal_units() -> dict[str, int]:
    return {"TP": 4, "PP": 4, "DP": 4}


def policy_label(depths: dict[str, int], units: dict[str, int]) -> str:
    depth = f"D(TP{depths['TP']},PP{depths['PP']},DP{depths['DP']})"
    budget = f"U(TP{units['TP']},PP{units['PP']},DP{units['DP']})"
    return f"{depth} {budget}"


def collective_steps(axis: AxisSignature) -> int:
    if axis.axis == "PP":
        return 1
    return max(1, math.ceil(math.log2(max(2, axis.group_size))) * 2)


def axis_port_weight(axis: str) -> float:
    return {"TP": 1.20, "PP": 0.80, "DP": 1.00}[axis]


def eval_policy(
    workload_name: str,
    sigs: dict[str, AxisSignature],
    regime: Regime,
    budget: Budget,
    policy_name: str,
    depths: dict[str, int],
    units: dict[str, int],
    ignore_port_loss: bool = False,
) -> EvalResult:
    failures: list[str] = []
    port_usage = 0.0
    max_loss = 0.0
    for axis in AXES:
        depth = depths[axis]
        spec = regime.depths[depth]
        if depth < sigs[axis].min_depth:
            failures.append("reach")
        if spec.loss_db > budget.loss_db and not ignore_port_loss:
            failures.append("loss")
        port_usage += axis_port_weight(axis) * units[axis] * spec.port_cost_per_unit
        max_loss = max(max_loss, spec.loss_db)
    if sum(units.values()) != TOTAL_RESOURCE_UNITS:
        failures.append("resource")
    if port_usage > budget.port_units and not ignore_port_loss:
        failures.append("port")
    if failures:
        return EvalResult(
            workload_name,
            regime.name,
            budget.loss_name,
            budget.port_name,
            policy_name,
            policy_label(depths, units),
            None,
            port_usage,
            max_loss,
            False,
            "+".join(sorted(set(failures))),
        )

    total = 0.0
    for axis in AXES:
        sig = sigs[axis]
        spec = regime.depths[depths[axis]]
        bandwidth_gbps = min(
            INJECTION_CAP_GBPS,
            spec.bandwidth_per_unit_gbps * units[axis],
        )
        data_s = (sig.payload_gb * 8e9) / (bandwidth_gbps * 1e9)
        latency_s = (spec.latency_us + spec.reconfig_us) * 1e-6
        control_s = latency_s * sig.events * collective_steps(sig)
        total += sig.critical_weight * (data_s + control_s)
    return EvalResult(
        workload_name,
        regime.name,
        budget.loss_name,
        budget.port_name,
        policy_name,
        policy_label(depths, units),
        total,
        port_usage,
        max_loss,
        True,
        "",
    )


def best_per_job_pathbudget(
    workload_name: str,
    sigs: dict[str, AxisSignature],
    regime: Regime,
    budget: Budget,
    ignore_port_loss: bool = False,
) -> EvalResult | None:
    candidates = [
        eval_policy(workload_name, sigs, regime, budget, "pathbudget", depths, units, ignore_port_loss)
        for depths in depth_assignments()
        for units in resource_allocations()
    ]
    feasible = [item for item in candidates if item.feasible and item.time_s is not None]
    if not feasible:
        return None
    return min(feasible, key=lambda item: item.time_s or float("inf"))


def best_static_policy_for_suite(
    workloads: list[WorkloadSpec],
    regime: Regime,
    budget: Budget,
) -> Policy | None:
    best: tuple[float, Policy] | None = None
    sig_by_workload = {workload.name: signatures(workload) for workload in workloads}
    for depths in depth_assignments():
        for units in resource_allocations():
            total = 0.0
            feasible = True
            for workload in workloads:
                result = eval_policy(
                    workload.name,
                    sig_by_workload[workload.name],
                    regime,
                    budget,
                    "best_static_locality_aware",
                    depths,
                    units,
                )
                if not result.feasible or result.time_s is None:
                    feasible = False
                    break
                total += result.time_s
            if feasible and (best is None or total < best[0]):
                best = (total, Policy("best_static_locality_aware", dict(depths), dict(units)))
    return None if best is None else best[1]


def failure_hist(
    workload: WorkloadSpec,
    regime: Regime,
    budget: Budget,
) -> dict[str, int]:
    sigs = signatures(workload)
    hist = {"reach": 0, "loss": 0, "port": 0, "resource": 0}
    for depths in depth_assignments():
        for units in resource_allocations():
            result = eval_policy(workload.name, sigs, regime, budget, "candidate", depths, units)
            if result.feasible:
                continue
            for part in result.failure_reason.split("+"):
                if part:
                    hist[part] = hist.get(part, 0) + 1
    return hist


def compare_against_baseline(
    baseline: EvalResult,
    pathbudget: EvalResult | None,
    oracle: EvalResult | None,
) -> ComparisonRow:
    if pathbudget is None or not pathbudget.feasible or pathbudget.time_s is None:
        speedup = None
        oracle_gap = None
        pb_label = "none"
        pb_time = None
        verdict = "pathbudget_infeasible"
    else:
        pb_label = pathbudget.depth_budget
        pb_time = pathbudget.time_s
        if baseline.feasible and baseline.time_s is not None:
            speedup = baseline.time_s / pathbudget.time_s
        else:
            speedup = None
        if oracle and oracle.time_s:
            oracle_gap = (pathbudget.time_s / oracle.time_s - 1.0) * 100.0
        else:
            oracle_gap = None
        if baseline.policy == "best_static_locality_aware":
            if speedup is None:
                verdict = "baseline_infeasible"
            elif speedup >= 1.10:
                verdict = "standalone_signal"
            elif speedup >= 1.05:
                verdict = "ablation_signal"
            elif speedup >= 0.98:
                verdict = "locality_ablation_only"
            else:
                verdict = "worse_than_static"
        else:
            verdict = "diagnostic"

    return ComparisonRow(
        workload=baseline.workload,
        regime=baseline.regime,
        loss_budget=baseline.loss_budget,
        port_budget=baseline.port_budget,
        baseline=baseline.policy,
        baseline_depth_budget=baseline.depth_budget,
        pathbudget_depth_budget=pb_label,
        baseline_time_s=baseline.time_s,
        pathbudget_time_s=pb_time,
        oracle_time_s=oracle.time_s if oracle else None,
        speedup=speedup,
        oracle_gap_pct=oracle_gap,
        verdict=verdict,
    )


def evaluate() -> tuple[list[dict[str, object]], list[ComparisonRow], list[dict[str, object]]]:
    workloads = workload_specs()
    workload_summary = [
        {
            "name": workload.name,
            "tp": workload.tp,
            "pp": workload.pp,
            "dp": workload.dp,
            "axes": {axis: asdict(sig) for axis, sig in signatures(workload).items()},
        }
        for workload in workloads
    ]
    rows: list[ComparisonRow] = []
    diagnostic: list[dict[str, object]] = []
    for regime in regimes():
        for budget in budgets():
            static_suite_policy = best_static_policy_for_suite(workloads, regime, budget)
            for workload in workloads:
                sigs = signatures(workload)
                pathbudget = best_per_job_pathbudget(workload.name, sigs, regime, budget)
                oracle = best_per_job_pathbudget(workload.name, sigs, regime, budget, ignore_port_loss=True)
                baselines: list[EvalResult] = [
                    eval_policy(
                        workload.name,
                        sigs,
                        regime,
                        budget,
                        "all_depth3_equal",
                        {"TP": 3, "PP": 3, "DP": 3},
                        equal_units(),
                    ),
                    eval_policy(
                        workload.name,
                        sigs,
                        regime,
                        budget,
                        "shortest_feasible_equal",
                        shortest_feasible_depths(sigs),
                        equal_units(),
                    ),
                    eval_policy(
                        workload.name,
                        sigs,
                        regime,
                        budget,
                        "fixed_locality_aware_equal",
                        {"TP": 1, "PP": 2, "DP": 3},
                        equal_units(),
                    ),
                ]
                if static_suite_policy is not None:
                    baselines.append(
                        eval_policy(
                            workload.name,
                            sigs,
                            regime,
                            budget,
                            static_suite_policy.name,
                            static_suite_policy.depths,
                            static_suite_policy.units,
                        )
                    )
                else:
                    baselines.append(
                        EvalResult(
                            workload.name,
                            regime.name,
                            budget.loss_name,
                            budget.port_name,
                            "best_static_locality_aware",
                            "none",
                            None,
                            0.0,
                            0.0,
                            False,
                            "no_suite_policy",
                        )
                    )
                for baseline in baselines:
                    rows.append(compare_against_baseline(baseline, pathbudget, oracle))
                diagnostic.append(
                    {
                        "workload": workload.name,
                        "regime": regime.name,
                        "loss_budget": budget.loss_name,
                        "port_budget": budget.port_name,
                        "best_static_suite_policy": asdict(static_suite_policy) if static_suite_policy else None,
                        "pathbudget": asdict(pathbudget) if pathbudget else None,
                        "oracle": asdict(oracle) if oracle else None,
                        "feasibility_failures": failure_hist(workload, regime, budget),
                    }
                )
    return workload_summary, rows, diagnostic


def selected_rows(rows: list[ComparisonRow]) -> list[ComparisonRow]:
    return [
        row
        for row in rows
        if row.baseline == "best_static_locality_aware"
        and row.loss_budget == "medium"
        and row.port_budget == "medium"
    ]


def summarize(rows: list[ComparisonRow]) -> dict[str, object]:
    strong_rows = [row for row in rows if row.baseline == "best_static_locality_aware"]
    feasible = [row for row in strong_rows if row.speedup is not None]
    medium = [
        row
        for row in feasible
        if row.loss_budget == "medium" and row.port_budget == "medium"
    ]
    medium_nonopt = [
        row
        for row in medium
        if row.regime == "reach_only_depth_is_costly"
    ]
    speedups = [row.speedup for row in feasible if row.speedup is not None]
    medium_speedups = [row.speedup for row in medium if row.speedup is not None]
    medium_nonopt_speedups = [row.speedup for row in medium_nonopt if row.speedup is not None]
    oracle_gaps = [row.oracle_gap_pct for row in feasible if row.oracle_gap_pct is not None]
    return {
        "total_resource_units": TOTAL_RESOURCE_UNITS,
        "injection_cap_gbps": INJECTION_CAP_GBPS,
        "average_speedup_vs_best_static_all_feasible": mean(speedups) if speedups else None,
        "average_speedup_vs_best_static_medium_budget": mean(medium_speedups) if medium_speedups else None,
        "average_speedup_vs_best_static_medium_nonoptimistic": mean(medium_nonopt_speedups)
        if medium_nonopt_speedups
        else None,
        "worst_case_speedup_vs_best_static": min(speedups) if speedups else None,
        "average_oracle_gap_pct": mean(oracle_gaps) if oracle_gaps else None,
        "num_best_static_rows": len(strong_rows),
        "num_best_static_feasible_speedups": len(feasible),
    }


def write_outputs(
    output_dir: Path,
    workload_summary: list[dict[str, object]],
    rows: list[ComparisonRow],
    diagnostic: list[dict[str, object]],
    calibration: list[dict[str, object]],
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "workload_signatures.json").write_text(json.dumps(workload_summary, indent=2, sort_keys=True))
    (output_dir / "comparisons.json").write_text(json.dumps([asdict(row) for row in rows], indent=2, sort_keys=True))
    (output_dir / "diagnostic.json").write_text(json.dumps(diagnostic, indent=2, sort_keys=True))
    (output_dir / "depth_assumptions.json").write_text(
        json.dumps(
            {
                "total_resource_units": TOTAL_RESOURCE_UNITS,
                "injection_cap_gbps": INJECTION_CAP_GBPS,
                "regimes": [
                    {
                        "name": regime.name,
                        "description": regime.description,
                        "depths": {str(depth): asdict(spec) for depth, spec in regime.depths.items()},
                    }
                    for regime in regimes()
                ],
                "budgets": [asdict(budget) for budget in budgets()],
            },
            indent=2,
            sort_keys=True,
        )
    )
    (output_dir / "astra_calibration_reused.json").write_text(json.dumps(calibration, indent=2, sort_keys=True))
    summary = summarize(rows)
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True))
    with (output_dir / "comparisons.csv").open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(asdict(rows[0]).keys()))
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))
    with (output_dir / "diagnostic.csv").open("w", newline="") as handle:
        flat_rows = []
        for item in diagnostic:
            pathbudget = item["pathbudget"] or {}
            oracle = item["oracle"] or {}
            static = item["best_static_suite_policy"] or {}
            flat_rows.append(
                {
                    "workload": item["workload"],
                    "regime": item["regime"],
                    "loss_budget": item["loss_budget"],
                    "port_budget": item["port_budget"],
                    "best_static_depths": static.get("depths"),
                    "best_static_units": static.get("units"),
                    "pathbudget_depth_budget": pathbudget.get("depth_budget"),
                    "pathbudget_time_s": pathbudget.get("time_s"),
                    "pathbudget_port_usage": pathbudget.get("port_usage"),
                    "pathbudget_loss_db": pathbudget.get("max_loss_db"),
                    "oracle_depth_budget": oracle.get("depth_budget"),
                    "oracle_time_s": oracle.get("time_s"),
                    "feasibility_failures": item["feasibility_failures"],
                }
            )
        writer = csv.DictWriter(handle, fieldnames=list(flat_rows[0].keys()))
        writer.writeheader()
        for row in flat_rows:
            writer.writerow(row)


def load_calibration(path: Path) -> list[dict[str, object]]:
    if not path.exists():
        return []
    return json.loads(path.read_text())


def fmt(value: float | None, suffix: str = "") -> str:
    if value is None:
        return "NA"
    return f"{value:.4f}{suffix}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "pathbudget_strong_followup")
    parser.add_argument(
        "--calibration-json",
        type=Path,
        default=REPO_ROOT / "pathbudget_feasibility" / "astra_calibration.json",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    workload_summary, rows, diagnostic = evaluate()
    calibration = load_calibration(args.calibration_json)
    write_outputs(args.output_dir, workload_summary, rows, diagnostic, calibration)

    print("ASTRA_CALIBRATION_REUSED")
    if not calibration:
        print("none")
    for item in calibration:
        print(
            f"{item['name']}\tfinished={item['finished_ranks']}/{item['ranks']}\t"
            f"cycles={item['max_cycles']}\ttimeout={item['timed_out']}"
        )

    print("\nDEPTH_ASSUMPTIONS")
    for regime in regimes():
        print(regime.name)
        for depth, spec in regime.depths.items():
            print(
                f"  depth{depth}: reach={spec.reach}, bw_per_unit={spec.bandwidth_per_unit_gbps}Gbps, "
                f"lat={spec.latency_us}us, port_per_unit={spec.port_cost_per_unit}, "
                f"loss={spec.loss_db}dB, reconfig={spec.reconfig_us}us"
            )
    print(f"total_resource_units={TOTAL_RESOURCE_UNITS}, injection_cap_gbps={INJECTION_CAP_GBPS}")

    print("\nSELECTED_MEDIUM_BUDGET_RESULTS_VS_BEST_STATIC")
    print("workload\tregime\tbaseline\tpathbudget\tbaseline_s\tpathbudget_s\toracle_s\tspeedup\tverdict")
    for row in selected_rows(rows):
        print(
            f"{row.workload}\t{row.regime}\t{row.baseline_depth_budget}\t{row.pathbudget_depth_budget}\t"
            f"{fmt(row.baseline_time_s)}\t{fmt(row.pathbudget_time_s)}\t{fmt(row.oracle_time_s)}\t"
            f"{fmt(row.speedup, 'x')}\t{row.verdict}"
        )

    print("\nSUMMARY")
    print(json.dumps(summarize(rows), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
